---
  - hosts: all
    gather_facts: false
    become: true

    vars:
      tmp_path: "{{ tmp_path }}"

    tasks:
      - name: Install Wazuh indexer
        command: "bash {{ tmp_path }}/wazuh-install.sh -wi {{ inventory_hostname }} -v"
        register: indexer

