---
  - hosts: all
    gather_facts: false
    become: true

    vars:
      test_name: "{{ test_name }}"
      tmp_path: "{{ tmp_path }}"
      test_dir: "/{{ test_name }}"
      logs_path: "{{ logs_path }}"
      system_name: "{{ system_name }}"

    tasks:
      - name: Create log directory
        file:
          path: "{{ test_dir }}"
          state: directory

      - name: Create log file
        file:
          dest: "{{ test_dir }}/{{ test_name }}_{{ system_name }}.log"
          state: touch

      - name: Install Wazuh
        block:

          - name: Install Wazuh server
            command: "bash wazuh-install.sh -ws {{ system_name }}-server -v"
            args:
              chdir: "{{ tmp_path }}"
            register: wazuh

        always:

          - name: Save output Wazuh
            blockinfile:
              marker: ""
              path: "{{ test_dir }}/{{ test_name }}_{{ system_name }}.log"
              block: |
                {{ wazuh.stderr }}
                --------------------------------
                {{ wazuh.stdout }}

          - name: Fetch log
            fetch:
              src: "{{ test_dir }}/{{ test_name }}_{{ system_name }}.log"
              dest: "{{ logs_path }}/"
              flat: yes
