---
- hosts: all
  become: true
  vars:
      script_path: "{{ tmp_path }}"
      script_name: "wazuh-install.sh"
      rpm_deps:
        - git
        - python3
        - python3-pip
        - openssl
        - tar
      apt_deps:
        - git
        - software-properties-common
        - gnupg2
      pip_deps:
        - attrs==21.1.0
        - importlib-metadata==4.8.2
        - iniconfig==1.1.1
        - packaging==21.3
        - pluggy==1.0.0
        - py==1.11.0
        - pyparsing==3.0.6
        - toml==0.10.2
        - typing-extensions==4.0.0
        - pytest==6.2.5
        - pyyaml
        - requests
        - setuptools
        - beautifulsoup4
        - urllib3==1.26.6

  tasks:
    - name: Make tmp folder directory
      file:
        path: "{{ tmp_path }}"
        state: directory

    - name: Install main deps block
      block:

        - name: Install required dependencies DNF
          dnf:
            name: "{{ rpm_deps }}"
            state: present
          when: ansible_os_family == 'RedHat'

        # ---------------------------------------------------------------------

        - name: Install required dependencies YUM
          yum:
            name: "{{ rpm_deps }}"
            state: present
          when: ansible_os_family == 'RedHat'

        # ---------------------------------------------------------------------

        - name: Install required dependencies APT
          apt:
            name: "{{ apt_deps }}"
            state: present
            update_cache: yes
          when: ansible_os_family == 'Debian'
      when:
        - install_deps is defined
        - install_deps | bool

    - name: Install Python and pip
      block: 

        # ---------------------------------------------------------------------
        # Ubuntu --------------------------------------------------------------

        - name: Set up Python 3.9 repository
          apt_repository:
            repo: 'ppa:deadsnakes/ppa'
          when:
            - ansible_os_family == 'Debian'
            - ansible_distribution == "Ubuntu"

        - name: Install Python3.9 on Ubuntu Jammy
          apt:
            name:
              - python3.9
              - python3.9-distutils
            state: present
            update_cache: yes
          when:
            - ansible_os_family == 'Debian'
            - ansible_distribution == "Ubuntu"
            - ansible_distribution_release == "jammy"

        - name: Change Python link Ubuntu Jammy
          command: ln -sf /usr/bin/python3.9 /usr/bin/python3
          when:
            - ansible_os_family == 'Debian'
            - ansible_distribution == "Ubuntu"
            - ansible_distribution_release == "jammy"

        - name: Change Python link Ubuntu Xenial
          command: ln -sf /usr/local/bin/python3.8 /usr/bin/python3
          when:
            - ansible_os_family == 'Debian'
            - ansible_distribution == "Ubuntu"
            - ansible_distribution_release == "xenial"

        # ---------------------------------------------------------------------
        # Pip installation ----------------------------------------------------

        - stat:
            path: /usr/bin/pip3
          register: stat_pip3
          when:
            - ansible_os_family == 'Debian'

        - name: Install pip Ubuntu\Debian
          shell: curl https://bootstrap.pypa.io/get-pip.py | python3 -
          when:
            - ansible_os_family == 'Debian'
            - stat_pip3.stat.exists == False
            - ansible_distribution_release != "xenial"
            - ansible_distribution_release != "focal"
            - ansible_distribution_release != "bionic"

        - name: Install pip Ubuntu Xenial
          shell: curl https://bootstrap.pypa.io/get-pip.py | python3 -
          when:
            - ansible_os_family == 'Debian'
            - stat_pip3.stat.exists == False
            - ansible_distribution_release == "xenial"

      when:
        - install_python is defined
        - install_python | bool

    # No version specified in pyyaml due to Xenial error.
    - name: Install pytest
      command: pip3 install {{ item }}
      with_items: "{{ pip_deps }}"
      when:
        - install_pip_deps is defined
        - install_pip_deps | bool

    - name: Clone installation assistant git repository
      git:
        repo: "{{ repository }}"
        dest: "{{ tmp_path }}"
        version: "{{ packages_reference }}"
        depth: 1
        force: true

    - name: Generate unattended
      command: "bash {{ tmp_path }}/builder.sh -i -d"

    - name: Change pre-release repository to selected one
      command: "sed -i 's|pre-release|{{ pkg_repository }}|g' {{ script_name }}"
      args:
        chdir: "{{ script_path }}"
